// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/bodokaiser/entgo-multi-tenancy/ent/runtime.go

const (
	Version = "v0.11.2-0.20220729101720-9673a4d5069a"           // Version of ent codegen.
	Sum     = "h1:pZLNhXt1OrdXWICexkb7E9ZVbQY4a2iBdTxafaSgZfM=" // Sum of ent codegen.
)
